// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// MerchantsColumns holds the columns for the "merchants" table.
	MerchantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeString},
		{Name: "dba", Type: field.TypeString},
	}
	// MerchantsTable holds the schema information for the "merchants" table.
	MerchantsTable = &schema.Table{
		Name:        "merchants",
		Columns:     MerchantsColumns,
		PrimaryKey:  []*schema.Column{MerchantsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeString},
		{Name: "firstname", Type: field.TypeString},
		{Name: "lastname", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UserOrderColumns holds the columns for the "user_order" table.
	UserOrderColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "merchant_id", Type: field.TypeInt},
	}
	// UserOrderTable holds the schema information for the "user_order" table.
	UserOrderTable = &schema.Table{
		Name:       "user_order",
		Columns:    UserOrderColumns,
		PrimaryKey: []*schema.Column{UserOrderColumns[0], UserOrderColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "user_order_user_id",
				Columns: []*schema.Column{UserOrderColumns[0]},

				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "user_order_merchant_id",
				Columns: []*schema.Column{UserOrderColumns[1]},

				RefColumns: []*schema.Column{MerchantsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MerchantsTable,
		UsersTable,
		UserOrderTable,
	}
)

func init() {
	UserOrderTable.ForeignKeys[0].RefTable = UsersTable
	UserOrderTable.ForeignKeys[1].RefTable = MerchantsTable
}
