// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Merchant is the predicate function for merchant builders.
type Merchant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
