// Code generated by entc, DO NOT EDIT.

package merchant

const (
	// Label holds the string label denoting the merchant type in the database.
	Label = "merchant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldDba holds the string denoting the dba field in the database.
	FieldDba = "dba"

	// EdgeMOrder holds the string denoting the m_order edge name in mutations.
	EdgeMOrder = "m_order"

	// Table holds the table name of the merchant in the database.
	Table = "merchants"
	// MOrderTable is the table the holds the m_order relation/edge. The primary key declared below.
	MOrderTable = "user_order"
	// MOrderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	MOrderInverseTable = "users"
)

// Columns holds all SQL columns for merchant fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldDba,
}

var (
	// MOrderPrimaryKey and MOrderColumn2 are the table columns denoting the
	// primary key for the m_order relation (M2M).
	MOrderPrimaryKey = []string{"user_id", "merchant_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
